-- Create all tables for AI Twitter Monitor

CREATE TABLE IF NOT EXISTS `users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openId` varchar(64) NOT NULL,
	`name` text,
	`email` varchar(320),
	`loginMethod` varchar(64),
	`role` enum('user','admin') NOT NULL DEFAULT 'user',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastSignedIn` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_openId_unique` UNIQUE(`openId`)
);

CREATE TABLE IF NOT EXISTS `ignoredTweets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`tweetId` varchar(64) NOT NULL,
	`tweetUrl` text,
	`ignoredAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ignoredTweets_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `runs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`runId` varchar(255),
	`status` enum('pending','running','success','failed') NOT NULL DEFAULT 'pending',
	`totalItems` int NOT NULL DEFAULT 0,
	`errorMessage` text,
	`triggeredBy` enum('manual','scheduled','telegram') NOT NULL DEFAULT 'manual',
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `runs_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `tweets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`runId` int NOT NULL,
	`tweetId` varchar(64) NOT NULL,
	`url` text NOT NULL,
	`text` text NOT NULL,
	`createdAt` timestamp NOT NULL,
	`language` varchar(10),
	`authorHandle` varchar(255) NOT NULL,
	`authorName` varchar(255),
	`authorProfileUrl` text,
	`authorProfileImageUrl` text,
	`authorCoverPhoto` text,
	`authorFollowersCount` int NOT NULL DEFAULT 0,
	`authorFollowingCount` int NOT NULL DEFAULT 0,
	`authorVerified` boolean NOT NULL DEFAULT false,
	`authorDescription` text,
	`authorJobTitle` text,
	`authorLocation` text,
	`authorWebsite` text,
	`authorJoinDate` text,
	`authorTweetsCount` int NOT NULL DEFAULT 0,
	`replyCount` int NOT NULL DEFAULT 0,
	`retweetCount` int NOT NULL DEFAULT 0,
	`quoteCount` int NOT NULL DEFAULT 0,
	`likeCount` int NOT NULL DEFAULT 0,
	`viewCount` bigint DEFAULT 0,
	`impressions` bigint DEFAULT 0,
	`mediaUrls` json,
	`mediaType` varchar(50),
	`quotedStatusId` varchar(64),
	`inReplyToStatusId` varchar(64),
	`hashtags` json,
	`mentions` json,
	`urls` json,
	`trendScore` int NOT NULL DEFAULT 0,
	`categories` json,
	`rawData` json,
	`fetchedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `tweets_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `fetchSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`searchTerms` text,
	`twitterContent` text,
	`queryType` varchar(20) DEFAULT 'Latest',
	`maxItems` int DEFAULT 200,
	`lang` varchar(10) DEFAULT 'en',
	`fromUser` varchar(255),
	`toUser` varchar(255),
	`mentionUser` varchar(255),
	`since` varchar(100),
	`until` varchar(100),
	`withinTime` varchar(50),
	`minRetweets` int DEFAULT 0,
	`minFaves` int DEFAULT 0,
	`minReplies` int DEFAULT 0,
	`minQuotes` int DEFAULT 0,
	`minViews` int DEFAULT 0,
	`filterMedia` int DEFAULT 0,
	`filterImages` int DEFAULT 0,
	`filterVideos` int DEFAULT 0,
	`filterLinks` int DEFAULT 0,
	`filterVerified` int DEFAULT 0,
	`filterSafe` int DEFAULT 0,
	`near` varchar(255),
	`within` varchar(50),
	`geocode` varchar(255),
	`filterReplies` int DEFAULT 0,
	`filterQuote` int DEFAULT 0,
	`filterNativeRetweets` int DEFAULT 0,
	`aiRewriteEnabled` int DEFAULT 0,
	`aiRewritePrompt` text,
	`telegramTemplate` text,
	`includeStats` int DEFAULT 1,
	`includeLink` int DEFAULT 1,
	`includeAuthor` int DEFAULT 1,
	`includeMedia` int DEFAULT 1,
	`includeDate` int DEFAULT 0,
	`isDefault` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fetchSettings_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `bookmarks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`tweetId` int NOT NULL,
	`note` text,
	`bookmarkedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `bookmarks_id` PRIMARY KEY(`id`)
);
