CREATE TABLE `fetchSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`searchTerms` text,
	`twitterContent` text,
	`queryType` varchar(20) DEFAULT 'Latest',
	`maxItems` int DEFAULT 200,
	`lang` varchar(10) DEFAULT 'en',
	`fromUser` varchar(255),
	`toUser` varchar(255),
	`mentionUser` varchar(255),
	`since` varchar(100),
	`until` varchar(100),
	`withinTime` varchar(50),
	`minRetweets` int DEFAULT 0,
	`minFaves` int DEFAULT 0,
	`minReplies` int DEFAULT 0,
	`filterMedia` int DEFAULT 0,
	`filterImages` int DEFAULT 0,
	`filterVideos` int DEFAULT 0,
	`filterLinks` int DEFAULT 0,
	`filterVerified` int DEFAULT 0,
	`filterSafe` int DEFAULT 0,
	`near` varchar(255),
	`within` varchar(50),
	`geocode` varchar(255),
	`filterReplies` int DEFAULT 0,
	`filterQuote` int DEFAULT 0,
	`filterNativeRetweets` int DEFAULT 0,
	`isDefault` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fetchSettings_id` PRIMARY KEY(`id`)
);
